# Generated by Django 5.2 on 2025-09-09 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('blocked', 'blocked'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Meduim', 'Meduim'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('issue_deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='employee.employee')),
            ],
        ),
    ]
