# Generated by Django 5.2.6 on 2025-09-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_comment_reviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
    ]
